/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#dae2fd",
        "on-primary-fixed-variant": "#004395",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#005236",
        "surface-container": "#eaedff",
        "secondary-fixed": "#6ffbbe",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "inverse-primary": "#adc6ff",
        "tertiary-container": "#a36700",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#424754",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#d2d9f4",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed-variant": "#653e00",
        "inverse-on-surface": "#eef0ff",
        "error": "#ba1a1a",
        "outline": "#727785",
        "surface-container-high": "#e2e7ff",
        "secondary": "#006c49",
        "on-tertiary-container": "#fffbff",
        "background": "#faf8ff",
        "secondary-container": "#6cf8bb",
        "on-primary-container": "#fefcff",
        "inverse-surface": "#283044",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-container": "#00714d",
        "primary": "#0058be",
        "primary-dark": "#0044cc",
        "surface-variant": "#dae2fd",
        "tertiary": "#825100",
        "on-primary-fixed": "#001a42",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-fixed": "#ffddb8",
        "on-tertiary": "#ffffff",
        "on-background": "#131b2e",
        "primary-container": "#2170e4",
        "error-container": "#ffdad6",
        "outline-variant": "#c2c6d6",
        "surface": "#faf8ff",
        "on-tertiary-fixed": "#2a1700",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed": "#002113",
        "surface-tint": "#005ac2",
        "primary-fixed": "#d8e2ff",
        "on-surface": "#131b2e",
        // Registration page specific styling aliases
        "surface-border": "#e2e8f0",
        "text-main": "#1a1f36",
        "text-muted": "#64748b",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "card": "1rem",
        "input": "0.5rem",
        "btn": "0.5rem",
        "badge": "9999px",
      },
      spacing: {
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "section-gap": "96px",
        "container-max": "1280px",
        "gutter": "24px",
        "unit": "8px",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-sm": ["'Plus Jakarta Sans'", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["30px", { lineHeight: "38px", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
      boxShadow: {
        "level-1": "0px 4px 20px rgba(15, 23, 42, 0.05)",
        "level-2": "0px 10px 30px rgba(15, 23, 42, 0.08)",
        "soft": "0 10px 40px -10px rgba(0,0,0,0.05)",
      },
      keyframes: {
        marquee: {
          '0%':   { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
      },
      animation: {
        marquee: 'marquee 28s linear infinite',
      },
    },
  },
  plugins: [],
};
